title: YouTube Influence Metrics - A Dashboard for Marketing Optimisation
description: An in-depth analysis of top UK YouTubers, leveraging Excel, Python, SQL and Looker Studio to create a comprehensive dashboard for data-driven marketing insights.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Optional settings
show_downloads: True



