title: Top UK Youtubers 2024 Project
description: A detailed project on top UK YouTubers using Excel, Python, SQL, and Looker Studio.
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Optional settings
show_downloads: True



