title: Top UK Youtubers 2024 Project
description: A detailed project on top UK YouTubers using Excel, Python, SQL, and Looker Studio.
theme: lanyon

# Optional settings
show_downloads: True
plugins:
  - jekyll-feed
